[program:api_offer]
command=/home/erpnext/api_offer_env/bin/gunicorn -c gunicorn.conf.py src.main:app
directory=/home/erpnext/.services/api_offer
user=erpnext
autostart=true
autorestart=true
stdout_logfile=/var/log/api_offer/supervisor.log
stderr_logfile=/var/log/api_offer/supervisor_error.log
environment=PYTHONPATH="/home/erpnext/.services/api_offer"
